'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BookMark
    Public Property BookmarkId As Integer
    Public Property BookmarkDescription As String
    Public Property BookmarklongDescription As String
    Public Property BookmarkProjectId As Integer
    Public Property BookmarkUserId As Integer
    Public Property BookmarkAnswer As String
    Public Property BookmarkQuestion As String
    Public Property BookmarkAnswerId As Nullable(Of Integer)
    Public Property BookmarkAnswerTypeId As Nullable(Of Integer)
    Public Property BookmarkSectionId As Nullable(Of Integer)
    Public Property Created As Date
    Public Property CreatedBy As String
    Public Property Updated As Nullable(Of Date)
    Public Property UpdatedBy As String

End Class
