'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClientBookmark
    Public Property ClientBookmarksId As Integer
    Public Property ClientId As Integer
    Public Property BookmarkId As String
    Public Property Created As Date
    Public Property CreatedBy As String
    Public Property Updated As Nullable(Of Date)
    Public Property UpdatedBy As String

End Class
