'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Client
    Public Property ClientId As Integer
    Public Property ClientFullName As String
    Public Property ClientTitle As String
    Public Property ClientFirstName As String
    Public Property ClientLastName As String
    Public Property ClientPassword As String
    Public Property ClientProject As String
    Public Property ClientProjectId As String
    Public Property ClientAddress As String
    Public Property ClientPhone As String
    Public Property ClientEmail As String
    Public Property ClientCompany As String
    Public Property ClientQuestions As String
    Public Property ClientEmailSubject As String
    Public Property ClientEmailBody As String
    Public Property AdminEmailAddress As String
    Public Property ClientProjectTemplate As String
    Public Property Created As Date
    Public Property CreatedBy As String
    Public Property Updated As Nullable(Of Date)
    Public Property UpdatedBy As String

End Class
