'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CompetitiveLandscape
    Public Property CompetitiveLandscapeId As Integer
    Public Property ProjectId As Integer
    Public Property ProjectName As String
    Public Property Company As String
    Public Property BrandName As String
    Public Property NonproprietaryName As String
    Public Property ClinicalTrialName As String
    Public Property ClassName As String
    Public Property PointsOfDifferentiation As String
    Public Property Created As Date
    Public Property CreatedBy As String
    Public Property Updated As Nullable(Of Date)
    Public Property UpdatedBy As String

End Class
