'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic

Namespace Models

    Partial Public Class PERSONAL_INFO
        Public Property id As Integer
        Public Property USERNAME As String
        Public Property PASSWORD As String
        Public Property FIRST_NAME As String
        Public Property LAST_NAME As String
        Public Property ADDRESS As String
        Public Property ADDRESS2 As String
        Public Property CITY As String
        Public Property STATE_PROVINCE As String
        Public Property ZIP As String
        Public Property COUNTRY As String
        Public Property CountryCode As Nullable(Of Integer)
        Public Property HOME_PHONE As String
        Public Property WORK_PHONE As String
        Public Property FAX As String
        Public Property EMAIL As String
        Public Property RESTYPE As String
        Public Property REFERRED_BY As String
        Public Property AGE As String
        Public Property SEX As String
        Public Property MARITAL_STATUS As String
        Public Property CHILDREN As String
        Public Property OCCUPATIONAL_FIELD As String
        Public Property TITLE_POSITION As String
        Public Property HOUSEHOLD_INCOME As String
        Public Property US_CITIZEN As String
        Public Property EDUCATION As String
        Public Property ETHNIC As String
        Public Property PRACTICE_TYPE As String
        Public Property AMA_ID As String
        Public Property BROWSER As String
        Public Property LAST_UPDATED As Nullable(Of Date)
        Public Property ssn As String
        Public Property paypal As String
        Public Property paypalemail As String
        Public Property active As String
        Public Property maiden As String
        Public Property nurse_class As String
        Public Property acct_username As String
        Public Property acct_restype As String
        Public Property program_code As Nullable(Of Integer)
        Public Property DOMAIN As String
        Public Property LIC_NUM As String
        Public Property LIC_STATE As String
        Public Property verified As String
        Public Property Smoke As String
        Public Property HowManyPacks As String
        Public Property Drink As String
        Public Property HowManyDrinks As String
        Public Property WillParticipate As String
        Public Property SignedUp As Nullable(Of Date)
        Public Property ReceiveEmail As String
        Public Property CheckedPreferences As String
        Public Property CheckedMedicalField As String
        Public Property Pets As String
        Public Property TestAccount As String
        Public Property AreYouAHuntingEnthusiast As String
        Public Property AreYouASportsEnthusiast As String
        Public Property Coded As String
        Public Property Add2 As String
        Public Property AlternateEmail As String
        Public Property Bounced As Nullable(Of Date)
        Public Property UsingAlias As String
        Public Property mag1 As String
        Public Property mag2 As String
        Public Property mag3 As String
        Public Property Agent As String
        Public Property RefID As String
        Public Property ValidEmail As String
        Public Property InvitationID As Nullable(Of Integer)
        Public Property HeardByPostcard As Nullable(Of Boolean)
        Public Property HeardByFax As Nullable(Of Boolean)
        Public Property HeardByPhone As Nullable(Of Boolean)
        Public Property HeardByFriend As Nullable(Of Boolean)
        Public Property HeardByColleague As Nullable(Of Boolean)
        Public Property HeardByOther As Nullable(Of Boolean)
        Public Property HeardOtherSpecify As String
        Public Property HeardByEmail As Nullable(Of Boolean)
        Public Property InvFaxNumber As String
        Public Property Notes As String
        Public Property active_ogr As String
        Public Property OldUsername As String
        Public Property MedicalSchool As String

    End Class
End NameSpace