'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ppr_ProjectListTable
    Public Property ppr_ProjectListId As Integer
    Public Property ProjectName As String
    Public Property SalesDate As Nullable(Of Date)
    Public Property LeadDirectorName As String
    Public Property BrandManager As String
    Public Property Split As String
    Public Property ProjectAmount As String
    Public Property ClientName As String
    Public Property Office As String
    Public Property Status As String
    Public Property Created As Date
    Public Property CreatedBy As String
    Public Property Updated As Nullable(Of Date)
    Public Property UpdatedBy As String

End Class
